server:
  port: 3050

db:
  file:
  #  持久化文件根路径
    filepath: D://hashdb
  #  每块数据文件的大小， 单位为字节
    chunk-size: 1 * 1024 * 1024
  #  全量保存数据库的间隔， 单位为毫秒
    save-interval: 1000 * 60 * 60 * 24
  ram:
    expired-key-delete-priority: LOW
    store-like-json-sequence: false

logging:
  level:
    root: INFO